# This is so stupid. Extnesions are blender devs inhumanity in man.
schema_version = "1.0.0"

id = "Gpencildrawswitcher"
version = "1.0.2"
name = "Grease Pencil: Draw switcher (eraser-switcher)"
tagline = "Hotkeys to switch between brushes and/or materials. Useful for using holdouts as an eraser. Make a keymap for gpencil.draw_switcher to use."
maintainer = "Splits285 <splits285@gmail.com>"
type = "add-on"

website = "https://github.com/Splits285/Gpencil_draw_switcher"
tags = ["Grease Pencil", "Materials", "Brush", "Eraser"]

blender_version_min = "2.8.0"
# blender_version_max = "5.1.0"

license = [
  "Unlicense",
]

# platforms = ["windows-amd64", "macos-arm64", "linux-x86_64"]
# Other supported platforms: "windows-arm64", "macos-x86_64"
